os:
  - linux
  - osx

sudo: false

language: go

go:
  - 1.9.x

install:
  - make deps

script:
  - go build

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false

env: GOTFLAGS="-race"
